version: "3.3"
services:
  jussi:
    restart: "no"
    image: "steemit/jussi:latest"
    ports:
      - "8080:8080"
    environment:
      #JUSSI_REDIS_URL: redis://redis1:6380
      LOG_LEVEL: ERROR
      JUSSI_DEBUG_ROUTE: "True"
    links:
      - redis1
    volumes:
      - /Users/muyloco/Dev/steemit/jussi/DEV_config.json:/app/DEV_config.json
  redis1:
    restart: "no"
    image: "redis:3.2"
    ports:
      - "6380:6379"
