version: "3.3"

services:
  jussi:
    restart: "no"
    image: "steemit/jussi:latest"
    ports:
      - "8080:8080"
    environment:
      JUSSI_REDIS_HOST: redis1
      JUSSI_REDIS_PORT: 6379
      JUSSI_REDIS_READ_REPLICA_HOSTS: redis2
      JUSSI_UPSTREAM_CONFIG_FILE: /app/ALT_config.json
    links:
      - redis1
      - redis2
  redis1:
    restart: "no"
    image: "redis:3.2"
    ports:
      - "6380:6379"
  redis2:
    restart: "no"
    image: "redis:3.2"
    ports:
      - "6379:6379"
